name: Build ISO and ARM Images (placeholder)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU (for ARM builds)
        uses: docker/setup-qemu-action@v2
      - name: Run build script
        run: |
          sudo bash scripts/build_iso.sh amd64
          sudo bash scripts/build_iso.sh arm64
